INSERT INTO artista (id,first_name, last_name, activo, correo, contraseña ) VALUES                                                                                                                                                            
(nextval('person_id_seq'),'Carmen', 'Lazo', true, 'carmen.lazo@gmail.com', '1234'),                                                                                                                                                           
(nextval('person_id_seq'),'Patricia', 'Benavides', true, 'patricia.benavides@gmail.com', '1234'),                                                                                                                                             
(nextval('person_id_seq'),'Martin', 'Vizcarra', true, 'martin.vizcarra@gmail.com', '1234'),                                                                                                                                                   
(nextval('person_id_seq'),'Pedro', 'Guzman', true, 'pedro.guzman@gmail.com', '1234'),                                                                                                                                                         
(nextval('person_id_seq'),'Pablo', 'Barnechea', true, 'pablo.barnechea@gmail.com', '1234'),                                                                                                                                                   
(nextval('person_id_seq'),'Luz', 'Martinez', true, 'luz.martinez@gmail.com', '1234'),                                                                                                                                                         
(nextval('person_id_seq'),'Miriam', 'Berrios', true, 'miriam.berrios@gmail.com', '1234'),                                                                                                                                                     
(nextval('person_id_seq'),'Marco', 'Polo', true, 'marco.polo@gmail.com', '1234'),                                                                                                                                                             
(nextval('person_id_seq'),'Julio', 'Lopez', true, 'julio.lopez@gmail.com', '1234'),                                                                                                                                                           
(nextval('person_id_seq'),'Martha', 'Diaz', true, 'martha.diaz@gmail.com', '1234');                                                                                                                                                           
                                                                                                                                                                                                                                              
INSERT INTO cancion (id,nombre, genero, reproducciones, fecha, calificacion_prom) VALUES                                                                                                                                                      
(nextval('cancion_id_seq'),'Bring Em Down', 'Alternativa/independiente, Rock', 4582, '01-01-2012', 4.5),                                                                                                                                      
(nextval('cancion_id_seq'),'Be quiet and drive(far away)', 'Heavy metal', 2150, '01-01-1997', 5),                                                                                                                                             
(nextval('cancion_id_seq'),'The hell song', 'Alternativa/independiente, Rock', 5680, '01-01-2002', 4.5),                                                                                                                                      
(nextval('cancion_id_seq'),'Butterflies and Hurricanes', 'Alternativa/independiente', 7593, '01-01-2001', 4.8),                                                                                                                               
(nextval('cancion_id_seq'),'Bombardero', 'rock', 2535, '01-01-2001', 4.5),                                                                                                                                                                    
(nextval('cancion_id_seq'),'Pardon Me', 'Nu metal', 6482, '01-01-2004', 3.9),                                                                                                                                                                 
(nextval('cancion_id_seq'),'I Bet You Look Good On The Dance Floor', 'Alternativa/independiente, Rock', 5642, '01-01-2005', 4.5),                                                                                                             
(nextval('cancion_id_seq'),'I need your love', 'Electro house', 9875, '01-01-2012', 4),                                                                                                                                                       
(nextval('cancion_id_seq'),'Runaway U', 'House', 11354, '01-01-2015', 4.5),                                                                                                                                                                   
(nextval('cancion_id_seq'),'Si Me Voy', 'rock', 1687, '01-01-2010', 3.5);                                                                                                                                                                     
                                                                                                                                                                                                                                              
INSERT INTO album (id,nombre, fecha) VALUES                                                                                                                                                                                                   
(nextval('album_id_seq'),'Weapons','01-01-2012'),                                                                                                                                                                                             
(nextval('album_id_seq'),'Around the Fur','01-01-2001'),                                                                                                                                                                                      
(nextval('album_id_seq'),'Does This Look Infected?','01-01-2002'),                                                                                                                                                                            
(nextval('album_id_seq'),'Absolution','01-01-2003'),                                                                                                                                                                                          
(nextval('album_id_seq'),'Bombardero','01-01-2001'),                                                                                                                                                                                          
(nextval('album_id_seq'),'Live in Japan 2004','01-01-2004'),                                                                                                                                                                                  
(nextval('album_id_seq'),'Whatever People Say I Am, Thats What Im Not','01-01-2006'),                                                                                                                                                         
(nextval('album_id_seq'),'18 Months','01-01-2012'),                                                                                                                                                                                           
(nextval('album_id_seq'),'Pharmacy','01-01-2015'),                                                                                                                                                                                            
(nextval('album_id_seq'),'Eres Nadie EP','01-01-2010');